# Generated by Django 3.0.4 on 2020-03-07 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=255, verbose_name='店名')),
                ('salon_email', models.EmailField(max_length=254, unique=True, verbose_name='店舗メール')),
                ('salon_password', models.CharField(max_length=125, verbose_name='パスワード')),
                ('home_page', models.URLField(unique=True, verbose_name='ホームページ')),
                ('salon_phone_num', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='電話番号は入力必須です。例:09012345678', regex='^[0-9]+$')], verbose_name='店舗電話番号')),
                ('salon_address', models.CharField(max_length=255, verbose_name='住所')),
                ('business_hours', models.CharField(max_length=255, verbose_name='営業日時')),
                ('cut_prise', models.IntegerField(verbose_name='カット料金')),
            ],
            options={
                'db_table': 'salon',
            },
        ),
    ]
